name = "ai-tarot-reading"
compatibility_date = "2024-09-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "dist"

# 明确告诉 wrangler 这是 Pages 项目（带 Functions）
# functions 目录会被自动检测并部署

[[d1_databases]]
binding = "DB"
database_name = "tarot-db"
database_id = "1446c20e-2a4d-4a63-8f4b-2111d08fdc81"
